  
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]  
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues project 1
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened' || contains(github.event.issue.labels.*.name, 'java-web')
        with:
          project: 'https://github.com/bobocode-projects/java-web-exercises/projects/1'
